### ISSUE TITLE
Secondary ticks

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#116]
Give the possibility to allow to draw secondary ticks. Those ticks will not be labelled but we could style them.

**Comment by NadjibSb** [comment]
is this what u mean ? 

![image](https://user-images.githubusercontent.com/25468825/105906397-eeb6a080-6023-11eb-891b-cccc024e1adc.png)

**Comment by NadjibSb** [comment]
what style's props should be visible to the user ?  Color is enough I think...
What do you suggest ?

**Comment by maasencioh** [comment]
If you could add a way to control the density and length I think that will be interesting

**Comment by targos** [comment]
I agree it could be useful to control the density but I would leave that to a separate PR.
For now, it should ideally be "smart" and intuitive for the reader. For example:
- Between 0.5 and 1, I would expect four secondary ticks (representing 0.6, 0.7, 0.8 and 0.9)
- Between 1 and 2, I would expect one secondary tick (representing 0.5)

**Comment by stropitek** [comment]
I agree with @targos 

Corollary:
- Between 0 and 5, 4 secondary ticks (1,2,3,4)
- Between 0 and 10, 1 secondary tick (5)

**Comment by NadjibSb** [comment]
> I agree it could be useful to control the density but I would leave that to a separate PR.
> For now, it should ideally be "smart" and intuitive for the reader. For example:
> 
> * Between 0.5 and 1, I would expect four secondary ticks (representing 0.6, 0.7, 0.8 and 0.9)
> * Between 1 and 2, I would expect one secondary tick (representing 1.5)

If we approach it this way, there will be too many cases to handle (big/small numbers, scientific).
I prefer controlling the density, it's much cleaner. 
The density value varies between 1..10 :
- density == 2 : one secondary tick representing 0.5
- density == 5 : four secondary ticks representing 0.2, 0.4, 0.6 and 0.8
- ...

**Comment by lpatiny** [comment]
We will see real cases but the following looks intuitive

![image](https://user-images.githubusercontent.com/1484241/105973291-d9c22780-608c-11eb-9bf6-d75b1768c6e4.png)

And actually it is even more complex because there are 2 levels of secondary ticks.

![image](https://user-images.githubusercontent.com/1484241/105973679-548b4280-608d-11eb-8a62-d8a814762fa4.png)

I would try at first that between the displayed labels (the previously selected primary ticks) we add 9 ticks and the fifth is lightly higher.

**Comment by stropitek** [comment]
@NadjibSb I think the ticks are an important problem and it's worth to spend some time working on an approach that "just works". I'm not against having a density prop or some other props that are relatively low level, but the value of that prop will in most cases not be passed by the user directly. It will be calculated with a function / hook based on axis domain and number of pixels available to the axis. 

We've done this for other projects (closed source so we cannot share unfortunately), but it's possible with a little bit of mathematics (think `Math.log10`, modulo) to come up with something generic that does not have to handle too many cases. We might have to use different "strategies" for different type of data (time for example must be handled differently), or for specific use cases. For now I think we can focus on the main scenario which is to show numbers under ticks in a way intuitive to humans, so multiples of 0.1, 0.2, 0.5,1,2,5 etc...

I agree with @lpatiny the result should depend on the number of pixels available on the axis.

**Comment by NadjibSb** [comment]
Should we give the user the ability to hide secondary ticks or it  dependents on the main Ticks (either show all ticks or hide them all) ?

**Comment by maasencioh** [comment]
I think that you could hide the secondary ticks with an option, but if you hide primary ticks, secondaries are hidden as well

**Comment by NadjibSb** [comment]
Of course, when the primary ticks are hidden, the secondary ticks are hidden as well.
I was asking if we give the user an option to show/hide secondary ticks (this option won't be taken in consideration if primary ticks are hidden).
The option will be True by default (show secondary ticks)

**Comment by maasencioh** [comment]
I think that you should add the option to hide, and the default being false instead.
