### ISSUE TITLE
Possibility to add error bars

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#133]
This applied to all Series (Scatter, Line)

Extend the data type to allow new optional number or array properties
- xError: this value will be used to draw vertical error bars
- yError: this value will be used to draw horizontal error bars

We may have the following example:
- xError:1 : symmetric error bar
- xError:[null, 0.7] : only one error bar on toward the high value
- yError: [1,2]: one error bar of 1 to the low value, one error bar of 2 to the high value

Take care to make the distinction between 0 and undefined. An error may be 0 and the error bar should still be drawn (actually only the cap). If it is undefined (or null) the error bar should be drawn. In order to check if the variable is undefined or null you should use `x == null`. The only exception where we are allowed to use `==` and not `===` ...

Error bars are drawn if the property `errorBars` is defined that has various properties.
```
errorBars: {
  style: {},
  capSize: 4, // in pixels
  capStyle: {}
}
```

Example of chart:

![image](https://user-images.githubusercontent.com/1484241/106284016-ef794d80-6242-11eb-954c-a3096c1e629d.png)

**Comment by NadjibSb** [comment]
When Error == 0 , should we add some height to the bar like image 1, or keep it like image 2 (in this case if vertical bars !=0 , horizontal bars wont appear at all)
![image](https://user-images.githubusercontent.com/25468825/106744768-7b62ef00-6620-11eb-80fe-e36524c3651e.png)
or 
![image](https://user-images.githubusercontent.com/25468825/106743719-0ba03480-661f-11eb-8946-20f58b4e5d0b.png)

**Comment by lpatiny** [comment]
I would not add some height. If it is 0 it should go through the center of the marker.

**Comment by NadjibSb** [comment]
The error bars should be bellow or above markers ?
