### ISSUE TITLE
Be able to display labels in scatter plot

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#151]
Should we allow a label property in a point ?

We would need to be able to style the label.

The position of the labels should be optimised in order to prevent overlap of labels and a line should be added between the label and the point.

![image](https://user-images.githubusercontent.com/1484241/110828266-28233280-8297-11eb-93d8-59446ecc99fc.png)

**Comment by lpatiny** [comment]
I have created a new dataset

[data.json.zip](https://github.com/zakodium/react-plot/files/7943232/data.json.zip)

That corresponds to:

![image](https://user-images.githubusercontent.com/1484241/151200834-241f6230-24bf-4db3-b389-73b9b662d11c.png)

The data does not contain the ellipses but only the scatter points. The ellipses can be calculated using `https://github.com/mljs/directional-distribution` and in order to prepare the 4 required ellipses the data can be preprocessed using the following code:

```js
const categories = 
    [... new Set(data.map(datum => datum.category))]
    .map(category => ({
        category,
        x: data.filter(datum => datum.category===category).map(datum => datum.x),
        y: data.filter(datum => datum.category===category).map(datum => datum.y),
    }));
```

@wadjih-bencheikh18 please could you replace the PCA example of ecstasy with this new dataset ? The main difference is that we will calculate directly in the storybook the ellipses based on the categories and that we will use 'DirectionalEllipse' annotations. There could be also the label for the categories in the middle of the ellipses.

Would be great if this example also allow to zoom (rectangular zoom).

Once this is done we will think about how to display the labels for each point in the scatter plot.

For completion, if ever we want to rebuild the dataset this is the code that can be used on www.c6h6.org:

```js
const pca = API.getData('pca');
const pcaAnnotations = API.getData('pcaAnnotations');
const ellipsis = API.getData('ellipsis');

const data = [];
for (let i=0; i<pca.x.length; i++) {
    data.push({
        label: pca.info[i].meta.TITLE,
        x: pca.x[i],
        y: pca.y[i],
        color: pca.info[i].meta.color,
        category:  pca.info[i].meta.category,
    })
}

const categories = 
    [... new Set(data.map(datum => datum.category))]
    .map(category => ({
        category,
        x: data.filter(datum => datum.category===category).map(datum => datum.x),
        y: data.filter(datum => datum.category===category).map(datum => datum.y),
    }));

console.log(categories);
```

**Comment by wadjih-bencheikh18** [comment]
@lpatiny how could I find ellipses in categories ? center , rx,ry,and angle

**Comment by lpatiny** [comment]
> @lpatiny how could I find ellipses in categories ? center , rx,ry,and angle

As explained in the issue you need to calculate those values using the project https://github.com/mljs/directional-distribution
