### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by maasencioh** [zakodium/react-plot#167]
We would consider 2 tracking options for scatter series, linear series, and bar series. The first one will be the closest existing point from all the series (this could be archived using a [Voronoi diagram](https://observablehq.com/@mbostock/the-delaunays-dual)).

The second option is to find the closest X value, considering X as the independent axis. This should return the closest value of all the series at the X-axis. The range series only should implement this case, returning the corresponding limits.

Will be needed to see the values of series when I move the mouse over a position in a plot, giving a [tooltip](https://airbnb.io/visx/docs/tooltip) or visual hint of the tracked position and the requested data, similar to this case https://airbnb.io/visx/xychart

![example](https://media.discordapp.net/attachments/750356712992800869/826788175376154645/unknown.png)

**Comment by lpatiny** [comment]
The react component should accept 2 properties:
- onMouseMove
- onClick

To which we will send a callback that is called with the following object:
{
  event,
  coordinates: {x1: 0, x2: 2, y1: 3},
  series: {
    a: {closestX, closestY, closest},
    b: {closestX, closedY, closest},
  }
}

Remarks:
- event is the dom event object and contains information like the position in pixel in the dom
- coordinates is the position of the mouse on all the axis in the axis units
- series is an object containing one property (the series ID) per series. Each series has the following property
  - closestX: the closest Point (we give back the object) considering only the X value
  - closestY: the closest Point considering only the Y value
  - closest: the closest Point (Euclidean distance)

**Comment by maasencioh** [comment]
There's no x and y axis, because this could be done in any of the elements of the axis array, so I'll propose the following change:

```
interface TrackingResults {
  event: HTMLEvent;
  coordinates: {
    [axisId: string]: Record<string, number>; // Ranges, errors, values, etc
  };
  series: {
    [seriesId: string]: { 
      [axisId: string]: SeriesPointType;
      closest: SeriesPointType; // Euclidean distance
    };
  };
};
```

The second thing is how to approach to this implementation, should it be inside the <svg> element?

**Comment by targos** [comment]
> The second thing is how to approach to this implementation, should it be inside the element?

You mean should it be inside `react-plot` ? Yes, I think we don't have a choice, as the information is all inside the component.
How I would approach it is by conditionally adding a layer (group) with the event handlers and the logic.

**Comment by targos** [comment]
For now, let's only focus on emitting the event, and the user can react to it (for example by updating an annotation)

**Comment by maasencioh** [comment]
Hello I want your opinion on the following thing. In react-plot the data is in a Series component, so if I want the closest point, because they are siblings, the components needs to connect through the father, that is Plot
```tsx
<Plot>
  <LineSeries data={data1} xAxis="x" yAxis="y" />
  <LineSeries data={data2} xAxis="x" yAxis="y" />
  <LineSeries data={data3} xAxis="x" yAxis="y" />
  <Axis id="x" position="bottom" />
  <Axis id="y" position="left" />
  <Tracking onMouseMove={/* Here I get the values */} />
</Plot>
```

What strategy will you follow for sending the nearest point of each series to the tracking? At this moment I think of two options: having a context for the data, where every data from every series is added, and then in the tracking I search over this context or create a reducer event, where the tracking component pushes every requested point, each series listen to this event and returns the closest point and then the tracking component only listen to this responses and merges.

**Example option 1:** useEffect on LineSeries add data1, data2 and data3 to `dataContext`, and in Tracking onMouseMove I search over `dataContext`

**Example option 2:** onMouseMove pushes {x, y} to the `closestContext` stack and each LineSeries adds its <key, value> that is close to that point

**Comment by targos** [comment]
Is there an advantage of using a `<Tracking>` component over just props on the Plot: `<Plot onMouseMove={}` ?

**Comment by maasencioh** [comment]
In a near future you could use render props for the tooltip, something like
```ts
<Tracking>
{ ({ coordinates }) => 
  <div style={{ left: coordinates.x, top: coordinates.y }} />
}
</Tracking>
```

**Comment by targos** [comment]
That's something else. I think the tracking itself should be exposed at the top level.

**Comment by maasencioh** [comment]
Ok, even changing to the top level, we have to communicate through context to the Series children. Should we create a specific context for this and each time that the event has triggered the children make the closest calculation, or should we send the data to the parent on each series mount and in each event search on this loaded data?

**Comment by targos** [comment]
It seems easier to handle this in the parent.

**Comment by stropitek** [comment]
If you add data to a context in the parent, don't forget to cleanup the context when the Serie unmounts

**Comment by maasencioh** [comment]
With closest, should we search for the closest over the scaled value or the value in pixels?

**Comment by targos** [comment]
I think the most intuitive for the user will be in pixels (closest to the mouse as viewed on the screen)
