### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by maasencioh** [zakodium/react-plot#168]
In order to have data exploration, is necessary to be able to zoom and pan zoom.
* Zooming is done relative to one or more axis, with the requirement that if there's more than one at least two of them are perpendicular. 
* A maximum and minimum can be set to the allowed zoom amount.
* Should be possible to center, begin or end of an axis.
* Should be possible to reset the zoom scale.

This actions could be link to different events, like double click, mouse wheel, mouse drag, or it could be linked to external event callbacks (a button for example)

References
* https://airbnb.io/visx/docs/zoom
* https://github.com/d3/d3-zoom

**Comment by targos** [comment]
We now have several hooks for zoom and are still working on it but I think we can close this specific issue.
