### ISSUE TITLE
Export only types

### ISSUE THREAD

**Issue by maasencioh** [zakodium/react-plot#170]
`common-spectrum` uses the types from this project, so currently, it needs to import everything from this project. What do you think to have something similar to `@types/zakodium-react-plot`?

**Comment by targos** [comment]
If you only need the types, you can use `import type ...` in TS

**Comment by maasencioh** [comment]
But in the install, I will need to install it as a dependency and all the co-dependencies, isn't it?

**Comment by targos** [comment]
Why does `common-spectrum` need the types from this project?
We cannot really do a `@types` because this is already a TypeScript project with types. We could publish some types separately but that would make it more difficult to maintain `react-plot`.

**Comment by maasencioh** [comment]
It's needed for generate the PlotObject

**Comment by targos** [comment]
Is there a problem with the dependencies? There shouldn't be too many of them, and they won't be included in front-end bundles I think.

**Comment by maasencioh** [comment]
Thank you
