### ISSUE TITLE
Dynamic layout

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#174]
I don't know how the space for number labels and axis labels are calculated but the default look is not ok.

![image](https://user-images.githubusercontent.com/1484241/114670587-7480e880-9d03-11eb-9a65-3279d2512a59.png)

I think the space used by the axis labels (number) should have an impact on the axis description and it has to be dynamically calculated. We should not have to fine tune some values to have a plot that looks ok.

**Comment by targos** [comment]
I have a pretty clear idea on how to do it, so I prefer to either do it or explain it before @maasencioh takes this issue.

**Comment by maasencioh** [comment]
I think we talked a bit about this for react-d3-utils, isn't it?

**Comment by targos** [comment]
Yes, this is probably going to need the `useBBoxObserver` hook from react-d3-utils.
