### ISSUE TITLE
Multiple display of an axis

### ISSUE THREAD

**Issue by maasencioh** [zakodium/react-plot#178]
The current way to show the same axis at top and bottom is to do something like
```tsx
<Axis position="top" id="x" />
<Axis position="bottom" id="x" />
```

The problem is that if any of the axes is removed, the other axis is removed from the context. I think of two options:
1. It should be checked if there's another axis with the same id before removing it from the context
2. An axis could accept several positions (non-orthogonal between them)

What do you think? @targos @lpatiny @stropitek @Sebastien-Ahkrin

**Comment by targos** [comment]
I think we need to support the same axis id multiple times (for example if you want to pass different options to display it).
What about keeping a "reference counter" in the state and only remove the axis from the context when the counter reaches zero?

**Comment by maasencioh** [comment]
Because properties like min or max could generate a conflict, is proposed a `<ParallelAxis>` component with the following properties:

```ts
type ParallelAxis= Omit<AxisProps, 
  | 'position' // infered from id
  | 'min'
  | 'max'
  | 'paddingStart'
  | 'paddingEnd'
  | 'flip'
  | 'scale'
>
```

This axis will only be displayed if `id` is defined in the `axis context and the position is inferred from the current position of the parent axis.

**Comment by targos** [comment]
sgtm!
