### ISSUE TITLE
Annotations on PlotObject

### ISSUE THREAD

**Issue by maasencioh** [zakodium/react-plot#181]
Some annotations are either generated from metadata (ex. peak picking) or in an interactive way (ex. tracking), so I propose to have these two additions

### PlotObject children
For interactive or complex annotations (for example groups) we could simply use children
```tsx
<PlotObject plot={plot}>
  {/* Only annotations are allowed as children */}
  <Annotation.Group {...dynamicProps}>
    <Annotation.Text>Hello, World!</Annotation.Text>
    <Annotation.Arrow x1="0" x2="100" y1="10" y2="10" endPoint="triangle" />
  </Annotation.Group>
</PlotObject>
```

### Annotation schema
If were generated in a previous step this could be added to the single property
```ts
type AnnotationsType = 
  // This for each annotation option
  | { type: 'circle' } & CircleProps
  | { type: 'arrow' } & ArrowProps
  // Group of annotations only
  | { type: 'group', children: Array<AnnotationsType>} & Omit<GroupProps, 'children'>

interface ReactObjectType {
  annotations: AnnotationsType[];
}
```

**Comment by targos** [comment]
`AnnotationsType` LGTM but one of the goals of annotations is to be able to interleave them with series. For example, have a base layer with some annotations, then some series, then another layer with other annotations. The layering is not really implemented yet, but we need to take it into account for the plot object design.

**Comment by maasencioh** [comment]
Should we add then a "z-index" like property or "merge" them in the series array? As you say that should be added to the current Plot implementation because now all the annotations are over the series

**Comment by targos** [comment]
The idea was that it would follow the JSX order, like in SVG.

**Comment by maasencioh** [comment]
That was what I meant with "merge", something like
```ts

type ContentType = 
  // This for each annotation option
  | { type: 'circle' } & CircleProps
  | { type: 'arrow' } & ArrowProps
  // Different series
  | ({ type: 'line' } & LineSeriesProps)
  | ({ type: 'scatter' } & ScatterSeriesProps)
  // Group of annotations only
  | { type: 'group', children: Array<AnnotationsType>} & Omit<GroupProps, 'children'>

interface ReactObjectType {
  content: ContentType []; // Merged series and annotations, will be added in the same order
}
```

**Comment by targos** [comment]
Something like that would work, yes.
At the top level I think we can have the same as in JSX for annotations: a single `{ type: 'annotations' }` with children.

**Comment by maasencioh** [comment]
Indeed seems cleaner like that
```ts
type AnnotationsType = 
  // This for each annotation option
  | { type: 'circle' } & CircleProps
  | { type: 'arrow' } & ArrowProps
  // Group of annotations only
  | { type: 'group', children: Array<AnnotationsType>} & Omit<GroupProps, 'children'>;

type ContentType = 
  | { type: 'annotation', children: Array<AnnotationsType> } 
  // Different series
  | ({ type: 'line' } & LineSeriesProps)
  | ({ type: 'scatter' } & ScatterSeriesProps)

interface ReactObjectType {
  content: ContentType []; // Merged series and annotations, will be added in the same order
}
```
