### ISSUE TITLE
Interactive histogram selector

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#187]
I would need something like this for the NMRium component.

@targos Do you think it should be an application of react-plot or rather a new component ?

Or should we rather use an existing component like https://samhogg.github.io/histoslider/?selectedKind=Histoslider&selectedStory=Open&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel ?

![2021-04-25 14 04 01](https://user-images.githubusercontent.com/1484241/115992749-9285fd00-a5cf-11eb-94bd-8a855a480c02.gif)

This will allow to select the contour plot levels based on the histogram of the noise of the spectrum.

**Comment by targos** [comment]
This should be a separate component or use something that exists already

**Comment by lpatiny** [comment]
Ok thanks.
