### ISSUE TITLE
New props for axis

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#192]
It would be nice to have the following props on the axis:
* units
* unitsWrapperBefore: default `(`
* unitsWrapperAfter: default `)`

By default what would be displayed on the axis:
* if there is a `units`: label + unitsWrapperBefore + units + unitsWrapperAfter
* if there is no `units`: label

@targos Is this ok for you ?
@maasencioh could you implement this ?

I changed https://github.com/cheminfo/common-spectrum to go in this direction to well separate in a `Variable` the units from the label.

**Comment by targos** [comment]
> unitsWrapperBefore: default (
> unitsWrapperAfter: default )

Is there any case where the wrapper before would not be the opposite of the wrapper after?

**Comment by lpatiny** [comment]
I don't think so.

It would rather be `()`, `[]` or maybe `<>`.

I'm just not sure that there is no case where there could be 2 symbols to open and close like `<<` and `>>` (I have no real case in mind) so this is why I was thinking about 2 properties.

However I think it will always be the same number of opening and closing symbols so we could have one property:

`unitsWrapper` and internally split it in 2 based on the length to have opening and closing part.

**Comment by targos** [comment]
Yes, I prefer one property.

**Comment by lpatiny** [comment]
@maasencioh so the goal would be to have 2 new properties:
* units
* unitsWrapper: default `()`

BTW @kjappelbaum point me to this link https://academia.stackexchange.com/questions/18357/are-there-any-guidelines-for-labeling-axes-in-plots-graphs. I was using square brackets to show the units but apparently this is wrong and we should use parenthesis. This is why the default is `()`

**Comment by kjappelbaum** [comment]
To quote from the link you posted: 
>The recommended way, according to the International System of Units (SI), is to write t/s (SI brochure, §5.3; see also this guide, §7.1). And the SI is the only system of units that should be used to report experimental results. 

But most major scientific journals use `()` indeed. Using `/` however makes sense in the context of [quantity calculus](https://iopscience.iop.org/article/10.1088/0026-1394/31/6/001/pdf) which is still widely used, e.g., in Chem Eng (e.g., to derive dimensionless numbers)

**Comment by lpatiny** [comment]
Indeed I was not aware of this `/` delimiter for units. Kevin suggests to use `unitsTemplate` to give full flexibility.

`unitsTemplate` could be something like `/ $1` or ` ($1)` but I guest there could be a better template format that we would use in all our projects.  

@targos do you think it is a good idea ?

**Comment by targos** [comment]
TBH, I don't really understand why you want to put this complexity on the `react-plot` side. From my point of view, the axis label should already be correctly formatted when it's passed to the component.

**Comment by lpatiny** [comment]
ok
