### ISSUE TITLE
Polyline and polygon annotations

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#198]
Add those 2 new annotations 

```jsx
<Annotation.Polyline points={[{x:1,y:2},{x:1,y:4},{x:2,y:7},{x:3,y:8}]}>
```

or as string

```jsx
<Annotation.Polyline points={[{x:"10",y:"20"},{x:"10",y:"40"},{x:"20",y:"70"},{x:"30",y:"48"}]}>
```

or a mixture of relative values to axis or absolute values in pixels

you can use line builder from d3

Same for Polygon, the only difference is that is it a closed surface and therefore can have a filled color.

In svg there are the corresponding polygon and polyline in svg and we accept all the style properties.

**Comment by lpatiny** [comment]
In the storybook we should also show a mixture of the number and string positions. One polyline may have partly numbers and partly strings.

**Comment by targos** [comment]
It would be surprising if only one type of annotation (polygon) cannot have mixed types.
