### ISSUE TITLE
Create an advanced mass example

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#200]
We would need a new example in the category 'mass'. This example should be called 'High resolution'

![image](https://user-images.githubusercontent.com/1484241/147344078-c75a82eb-f3e7-4c5c-ab97-170e0dd29b7d.png)

This example will use the following JSON: https://github.com/zakodium/react-plot/blob/main/scripts/mass/HCys100OH_0.01.json

This JSON has 3 properties:
- profile = LineSeries
- centroid = BarSeries
- bestPeaks = A group annotation composed on a line and 2 texts

Horizontal axis: 'Mass (m/z)'
Vertical axis: 'Relative intensity (%)'

The result should be something similar to 

![image](https://user-images.githubusercontent.com/1484241/147345072-b91ed9b6-137a-480d-b670-3989217c4e10.png)

For the annotations on the top of the peaks we will use 'bestPeaks':
- x / y decides the position
- we will keep 5 pixels between the x position and a line
- the label will be composed of:
  - x.toFixed(4)
  - shortLabel
- the label will be placed on the right of a vertical line (2 px from the line)

**Comment by wadjih-bencheikh18** [comment]
@lpatiny would u please generate anouther exmple of data 

**result of previous data :**

![image](https://user-images.githubusercontent.com/56769876/148683778-a7721aae-a1e2-44c5-8e4a-5bb349740d71.png)

**Comment by lpatiny** [comment]
The result is correct. By adding a the possibility to enter min / max value on the xAxis you will get the same image as the one in this issue.

**Comment by wadjih-bencheikh18** [comment]
> The result is correct. By adding a the possibility to enter min / max value on the xAxis you will get the same image as the one in this issue.

Okey, thanks
