### ISSUE TITLE
Props names depend on the kind of annotation

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#204]
Currently the props names are closely related to the SVG prop name. While it make sense we are not expecting that the users of react-plot know SVG.

For example a `shape` will be centred on the properties `x` and `y` while a circle would be centred on `cx` and `cy`

Similarly a line would go from x1,y1 to x2,y2 while a rectangle would have x,y,width,height

I would make it more homogenous and use:

- for circle, ellipse and shape: x and y
- for line and rectangle: x1,y1 x2,y2

**Comment by lpatiny** [comment]
What about the other props, `fill`, `stroke-color`, ...

- if text: color => fill
- if line: color => stroke
- if rectangle: color => fill

We would then forbid to add the SVG property

**Comment by maasencioh** [comment]
Then are we going to limit SVG properties or only rename the ones that you have mentioned?

**Comment by targos** [comment]
For now we thought of only forbidding the ones that conflict, so it would still be possible for example to pass `stroke` on a rectangle to set the color of the border

**Comment by wadjih-bencheikh18** [comment]
> 
@lpatiny 
just text,line and rectangle ? or all annotation components

**Comment by lpatiny** [comment]
> just text,line and rectangle ? or all annotation components

Need to check if it make sense for the other annotations as well indeed.

**Comment by wadjih-bencheikh18** [comment]
I added color props to shape , circle and ellipse annotations
