### ISSUE TITLE
Add PCA example with ellipse showing the SD

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#208]
We would need to generate such a plot:

![image](https://user-images.githubusercontent.com/1484241/148266939-3f9409eb-ae09-4d5f-9ae1-b731810ba6ac.png)

A scatter plot with some ellipse annotations and labels that could use a force field in order to be nicely placed.

**Comment by lpatiny** [comment]
Just for documentation the example data was created on www.c6h6.org in the PCA view with the XTC data set using the following code executor:

```js
const pca = API.getData('pca');
const ellipsisData = API.getData('ellipsis');

console.log(pca);

const points = [];
for (let i=0; i<pca.x.length; i++) {
    points.push({
        x:pca.x[i],
        y:pca.y[i],
        color:pca.styles.unselected[i],
        id:pca.info[i].meta.TITLE,
    });
}

const ellipses=[];
for (let i=0; i<ellipsisData.length; i++) {
    console.log(ellipsisData);
    ellipses.push({
        x:ellipsisData[i].properties.position[0].x,
        y:ellipsisData[i].properties.position[0].y,
        rx:ellipsisData[i].properties.rx,
        ry:ellipsisData[i].properties.ry,
        fillColor:ellipsisData[i].properties.fillColor,
        fillOpacity:ellipsisData[i].properties.fillOpacity,
        label:ellipsisData[i].properties.labelText[0],
        angle:ellipsisData[i].properties.transforms[0].angle,
    })
}

const data = {
    points,
    ellipses,
}

console.log(data);
```

**Comment by lpatiny** [comment]
There is now a [dataset](https://github.com/zakodium/react-plot/blob/ad44fd81b28c83d4075406a46acab5e0fb850ee3/stories/data/pca.json) that contains 2 properties:

- points: the data to create the scatter plot
- ellipses: the ellipses to draw with an opacity of 0.2

In this example the points of the scatter plot should have different colors. I think we should in fact not use a scatter plot series but only use annotations. For the points. circle annotations. and ellipse annotation for the ellipses.

**Comment by targos** [comment]
> I think we should in fact not use a scatter plot series but only use annotations.

Why?

**Comment by lpatiny** [comment]
I have the impression that currently all the points of a scatter series have the same shape, size and color.

For this example if we are not using annotations to display all the points we would then either create 5 scatter series (one per color) or allow for each point in the series to not only specify `x` and `y` but also `size` or `color` or `style`.

**Comment by targos** [comment]
It is possible to do it with only one scatter series and a callback for the color.

**Comment by lpatiny** [comment]
@wadjih-bencheikh18 Based on targos comment please could you try to implement this storybook ?

So one scatter series with call back with colors and then annotation for the ellipses.

**Comment by wadjih-bencheikh18** [comment]
okey it's clear yes

**Comment by wadjih-bencheikh18** [comment]
![image](https://user-images.githubusercontent.com/56769876/149170415-7485ce3d-4a0d-4552-85c7-79be91cb69f1.png)
we can see that when i used scatter axis min/max are not perfect

**Comment by lpatiny** [comment]
This is not a problem and would consider it as expected.

Please use for all the axis a paddingStart, paddingEnd of 0.1

https://github.com/zakodium/react-plot/blob/main/src/components/Axis/Axis.tsx#L18-L19

**Comment by wadjih-bencheikh18** [comment]
there is also another problem
![image](https://user-images.githubusercontent.com/56769876/149174181-ddcfeb99-81d5-4e19-a6cf-bd21342a4941.png)
ellipses center are not in the right place
(the two lines are just used to know the center)

**Comment by wadjih-bencheikh18** [comment]
> 

problem fixed

**Comment by targos** [comment]
@lpatiny  Is it normal that the data is different from your screenshot?

**Comment by wadjih-bencheikh18** [comment]
> @lpatiny Is it normal that the data is different from your screenshot?

i think it's not the same data

final result : 
![image](https://user-images.githubusercontent.com/56769876/149181956-044741eb-ea09-4cd0-ac87-76b330e8d7b1.png)

**Comment by lpatiny** [comment]
> @lpatiny Is it normal that the data is different from your screenshot?

Should not but apparently I did a mistake.

**Comment by wadjih-bencheikh18** [comment]
@lpatiny could you give me axis labels please?
