### ISSUE TITLE
Tick labels outside the plot area

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#209]
@targos we discussed about this problem but not sure that we decide about a solution.

Sometimes the tick labels are outside the drawing area which may be quite annoying.

![image](https://user-images.githubusercontent.com/1484241/148349529-3d80ccb4-8c52-4840-acfa-0d9e15603e8d.png)

I think the simplest solution in this case is simply not to draw those labels. If the user really want those labels he would have to add some padding.

**Comment by targos** [comment]
The yellow rectangle is here for debugging. Once we remove it, I'm not sure it will really be ugly to let the label overflow a little.
As you said, the user can add some global padding or `overflow: hidden`.
