### ISSUE TITLE
Review and implement all missing axis props

### ISSUE THREAD

**Issue by targos** [zakodium/react-plot#214]

**Comment by maasencioh** [comment]
why?

**Comment by targos** [comment]
because in https://github.com/zakodium/react-plot/pull/203 I completely rewrote axis rendering (using 2 components instead of 8) but I didn't reimplement all the functionality.

**Comment by targos** [comment]
For example: `tickPosition` and `primaryTickLength` need to be implemented.

**Comment by targos** [comment]
Props are defined here: https://github.com/zakodium/react-plot/blob/352dfe57b601b1dd225bffb8c4e7114e6d3072f0/src/components/Axis/Axis.tsx#L10
