### ISSUE TITLE
Add a callback in the axis component to format tick labels

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#218]
Could we add a callback in the axis component that would format the value ? 

`tickLabelFormat: (value) => value.toFixed(2)`

- remove property `scientific`
- add a new property call `tickLabelFormat`
- default callback: `(value) => String(value)`

**Comment by targos** [comment]
Done in https://github.com/zakodium/react-plot/commit/352dfe57b601b1dd225bffb8c4e7114e6d3072f0
