### ISSUE TITLE
Annotation only example

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#222]
I don't know how are the min / max values calculate if there are only annotations and no series.

I think the min / max default values on the axes should take into account the position of all the annotations for which positions are defined as number (and therefore values on the axes).

We should first close this issue: https://github.com/zakodium/react-plot/issues/204

We could add first in the storybook an example with only 4 circles in position 1,1 - 2,2 - 1,2 and 2,1 to test.

**Comment by lpatiny** [comment]
Because positions are stored differently in circle, line, rectangle, polyline, etc it may be useful to get for each annotation a 'getBoundingRectangle' method.

**Comment by targos** [comment]
That's not going to be easy for text and groups. I fear this is a very difficult issue to solve.

**Comment by targos** [comment]
Do you have a real use case where it makes sense to not have a series and where you don't know the min/max ?

**Comment by lpatiny** [comment]
I was actually thinking about the PCA example https://github.com/zakodium/react-plot/issues/208.

**Comment by wadjih-bencheikh18** [comment]
> I was actually thinking about the PCA example #208.

it's possible to calculate min,max in this exmple

**Comment by lpatiny** [comment]
I think that if we want to implement this feature we could only use the `x` like (x, x1, y1, array of the x for polyline, etc) and `y` like coordinates so we don't care about radius of circle, text size, etc.  We would need to add some padding if we are drawing circles and we would like they are not cut on a side.

So text and groups would only be considered as a point and only if the position is specified as numbers (relative to axes)

**Comment by wadjih-bencheikh18** [comment]
i think we can use circle radius ....etc for diffrent annotations
and about the group we can take his children
but text i think the only solution is consider it as a point (as u mentioned)

**Comment by lpatiny** [comment]
Currently we will not implemented it because annotations are not tracked in the state.
