### ISSUE TITLE
Add color prop to Annotation.Arrow

### ISSUE THREAD

**Issue by targos** [zakodium/react-plot#227]

**Comment by wadjih-bencheikh18** [comment]
i tried to fix this but I didn't find a way to color Markers  [MarkerDefs](https://github.com/zakodium/react-plot/blob/87d8af6d33c465a53b69dd07fe90e2fb15812cbe/src/components/Annotations/MarkerDefs.tsx)

**Comment by targos** [comment]
It seems possible in SVG 2 with `context-fill` / `context-stroke` but I don't know what is the browser support for this:
https://svgwg.org/svg2-draft/painting.html#Introduction

Otherwise, the solution might be to define specific markers with the correct color inside each arrow.
