### ISSUE TITLE
Fix result when color prop is empty in annotations

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium/react-plot#232]
we can see in line when color="" the line disappear
but in text, circle .. the annotation color turns black

**Comment by targos** [comment]
Problem is with Line, Polygon and Arrow. I think we can just do something like `stroke={color || 'black'}` for them?

**Comment by wadjih-bencheikh18** [comment]
color="" ( not undefinded)  I think the right result must me nothing (no color)

**Comment by targos** [comment]
We can also decide to not support it (do nothing) because `color="none" ` is better and works already

**Comment by wadjih-bencheikh18** [comment]
So we have to disable empty string color="" ? and set black as default color?

**Comment by targos** [comment]
Black is already the default color. I'd say we should just consider an empty string to be unsupported and ignore it (and close this issue)
