### ISSUE TITLE
Should we add a 'rotate' property to all the annotations

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#234]
This property would be a shortcut to:
```
  transform-box: fill-box;
  transform-origin: center;
  transform: rotate(45deg);
```

But will also take into account the fact that coordinates can be in pixel or in scale units and in case of scale units the rotation is not that simple ...

In order to debug and check that everything is ok we should take back the PCA example and add 2 lines annotations showing the 2 ellipse axes.

![image](https://user-images.githubusercontent.com/1484241/149285585-baba3a92-2cbc-45e2-82ce-49f94a82704b.png)

The `rotation` angle the angle to turn if the number of pixels per unit is the same on the horizontal axis and on the vertical axis. If it is not the same we need to calculate the new angle and this will be easy to debug if we draw the 2 ellipse axes.

Look for example at and check the major axis of the yellow ellipse:

![image](https://user-images.githubusercontent.com/1484241/149285805-40b35c70-eacc-4445-9d05-0fc6a0641e80.png)

If I zoom

![image](https://user-images.githubusercontent.com/1484241/149285888-de05c2af-6dd5-4de9-9fd4-a02750743f06.png)

We see that the major axes of the ellipse changed

![image](https://user-images.githubusercontent.com/1484241/149285934-dda340b3-9080-43a9-817a-9d4355908116.png)

**Comment by maasencioh** [comment]
In order for it to work, it should also be necessary to take into account that all the other transformations shouldn't be allowed to apply and implement them by our own, knowing that the order of them changes the result, and is not obvious to know in two different properties if you want to translate and then rotate or the opposite way. Could be interesting to have a transform property (`transform: Transform[]`) that applies the possible transformations in that given order.

**Comment by lpatiny** [comment]
DirectedAnnotation solve this problem
