### ISSUE TITLE
axis min / max and number versus string

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#242]
```jsx
    <Plot width={300} height={300}>
      <Axis position="bottom" min="0" max="10" />
      <Axis position="left" min="0" max="10" />
    </Plot>
```

I'm wondering why when we specify min and max as string we obtain

![image](https://user-images.githubusercontent.com/1484241/149384888-406016a9-ee44-408a-89cc-49d38cde37e5.png)

While if we specify it as number

```jsx
    <Plot width={300} height={300}>
      <Axis position="bottom" min={0} max={10} />
      <Axis position="left" min={0} max={10} />
    </Plot>
```

We obtain the correct plot

![image](https://user-images.githubusercontent.com/1484241/149385130-78019dfe-e33e-47b6-a2d0-4481de09a525.png)

@targos Is this the expected behaviour ?

**Comment by targos** [comment]
It's not allowed to pass strings, so the behavior is undefined.

**Comment by targos** [comment]
The reason it becomes `100` in your example is because the value is added to the padding, which is `0`. `"10" + 0 === "100"`
