### ISSUE TITLE
Improved advanced mass spectrum example to add pan and vertical scale

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#251]
https://zakodium.github.io/react-plot/?path=/story/experimental-spectra-mass--advanced-mass-example

For this example we could use the scrollWheel to vertically scale the spectrum (and keep the double click to reset both the horizontal and vertical scale)

**Comment by lpatiny** [comment]
@wadjih-bencheikh18 Please not only implement vertical scaling but also pan.

When we press the ALT the mouse cursor should change in a hand and you should be able to click + drag the spectrum (pan). So no zoom in this case but vertical and horizontal shift of the spectrum.

**Comment by wadjih-bencheikh18** [comment]
> vertically scale

i think scrollWheel is not a good option to zoom (we better use any key(shift for exmple)+ scroll)

**Comment by lpatiny** [comment]
We can always add a modifier later but in this example I would like without modifier. This is what we use in most of our applications currently. It is also the behaviour when you go on google maps for example.

**Comment by stropitek** [comment]
> i think scrollWheel is not a good option to zoom (we better use any key(shift for exmple)+ scroll)

It's a valid point because indeed you'll have an undesirable behavior when scrolling and hitting a plot with your mouse. But we'll often integrate the component in a page that does not have any scrolling bar so we still want to be able to zoom without a modifier.



> It is also the behaviour when you go on google maps for example.

Yes because there is nothing else than the map. When embedded in pages you cannot zoom with the mouse wheel.

**Comment by wadjih-bencheikh18** [comment]
> @wadjih-bencheikh18 Please not only implement vertical scaling but also pan.
> 
> When we press the ALT the mouse cursor should change in a hand and you should be able to click + drag the spectrum (pan). So no zoom in this case but vertical and horizontal shift of the spectrum.

I have a problem with ALT key 
in my browser alt change the focus to something else so sometimes it causes problems
