### ISSUE TITLE
Implement hook for horizontal zoom

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#259]
We would need a simple way to add the zoom functionality through a hook.

This hook `useHorizontalZoom` would take care of adding the rectangular annotation (with our new '0%' '100%' units and change the min/max accordingly.

For the drawing of the zoom rectangle it would be nice for the rectangle to be translucent and have no borders. On the left and right of the rectangle we would add 2 vertical lines (opacity: 1) (actually we just don't want to display the top and bottom side of the rectangle for horizontal zoom). 

We also need to deal with couple of possible issues:
- we start the zoom in the Plot component and we leave the component. The zoom should continue to work
- many hooks are listening to mouse move, for example we display crosshair with the X/Y values next to the crosshair.

@targos Does this make sense ?

**Comment by targos** [comment]
Need https://github.com/zakodium/react-plot/issues/285 first
