### ISSUE TITLE
DirectedEllipse

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#260]
The rotation of an ellipse is not easy because it has to be rotate around the center but also if the `rx` or `ry` is defined in the units of the axis the angle changes. It seems to be easier therefore to create a new annotation kind `DirectionalDistribution` that solves this issue.

The new kind of Ellipse (DirectedEllipse) is defined differently using `x1`, `y1`, `x2`, `y2` and `width`. Those 5 parameters can be defined using number, string or percent as with the other annotations.

![image](https://user-images.githubusercontent.com/1484241/149970535-eda16765-5925-4736-8324-bfe755572596.png)

@wadjih-bencheikh18 Are you able to implement this ?

We could use the following story book (I hope I didn't make too many mistakes). This storybook should also implement the zoom (and double click to zoom out) in order to check that everything is ok.

```
<Plot width={300} height={300}>
      <Annotations>
        <DirectedEllipse
          x1=40
          y1=40
          x2=60
          y2=60
          width=5
        />
        <Line
          x1=40
          y1=40
          x2=60
          y2=60
        />
        <Line
          x1=47.5
          y1=52.5
          x2=52.5
          y2=47.5
        />
      </Annotations>
      <Axis position="bottom" min={0} max={100} />
      <Axis position="left" min={0} max={100} />
    </Plot>
```

Reference: https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-statistics-toolbox/directional-distribution.htm

**Comment by stropitek** [comment]
The name seems oddly specific to the use case of showing statistical context.

Can we change to maybe `DirectedEllipse`?. I think at least "Ellipse" should stay in the name

**Comment by lpatiny** [comment]
No problem for me for `DirectedEllipse`. I quite like it.
