### ISSUE TITLE
re-implement secondary ticks

### ISSUE THREAD

**Issue by targos** [zakodium/react-plot#264]
Use the `secondaryTickLength` and `secondaryTickStyle` props to style them.

Old code is here: https://github.com/zakodium/react-plot/blob/6790221f798e20479aa1b03fb25a3924417bf4f0/src/components/Axis/Ticks.tsx#L52-L100

We decided to remove the `hiddenSecondaryTicks` prop. Instead the user can pass `secondaryTickLength={0}` if they don't want to see them.

**Comment by targos** [comment]
Default value for `secondaryTickLength` should be 2.

@wadjih-bencheikh18

**Comment by wadjih-bencheikh18** [comment]
i think we should add secondary ticks number

**Comment by targos** [comment]
You mean how many ticks to draw? Maybe, but we should first focus on good automatic values.

**Comment by wadjih-bencheikh18** [comment]
> You mean how many ticks to draw? Maybe, but we should first focus on good automatic values.

The value used is hard coded (5 or 10) depend on the density
