### ISSUE TITLE
Label not selectable

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#273]
Seems to me that the labels should not be selectable

![2022-01-25 19 02 23](https://user-images.githubusercontent.com/1484241/151033440-854d43bb-dbea-45a4-8b8e-7df4152671ee.gif)

**Comment by targos** [comment]
You mean the tick labels? Why?

**Comment by lpatiny** [comment]
The axis label is currently selectable but not the tick labels. If this is the expected behaviour it is ok to me. Just wanted to be sure it is normal.

**Comment by targos** [comment]
The tick labels have `user-select: none;` in their style. Maybe we should go further and also disable selection of the axis labels, or any text inside of the svgL

**Comment by lpatiny** [comment]
I would indeed add user-select:none on all the svg text elements.
