### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#292]
@fpatiny is fan of darkmode (me too). I'm wondering how we could implement this feature.

**Comment by targos** [comment]
`<svg style={{ filter: 'invert(1)' }}>` 😄 

Now seriously, how do you imagine that to work knowing that a lot of the colors come directly from the user of the library?

**Comment by lpatiny** [comment]
Didn't know this `filter` css property but it could be a first approach that could look pretty ok in react-plot.zakodium.com documentation.

![image](https://user-images.githubusercontent.com/1484241/151823357-7162d692-7c1a-4df9-b041-298f09291115.png)

**Comment by targos** [comment]
You could also remove dark mode from the documentation website.
