### ISSUE TITLE
Square zoom problem

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#297]
I square zoom when one of the direction is `0` size it will give strange results.

I tested it in the non merged [new PCA example](https://github.com/zakodium/react-plot/pull/286) but I guess it is a general problem

![image](https://user-images.githubusercontent.com/1484241/152100058-7ac01399-0b7e-413a-9f20-f97be56e385f.png)

So it the square zoom if one of the direction is `0` we should do nothing and this should be updated in all examples.

**Comment by stropitek** [comment]
@lpatiny I think it's pointless to spend time on this since all the stories will be refactored anyway when when we will be happy with the new apis @targos is working on. The code related to this bug will disappear.

**Comment by lpatiny** [comment]
Fixed using the hook PR
