### ISSUE TITLE
onEnd callback useDrawRectangle ?

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#310]
Should UseDrawRectangleOptions not have an onEnd callback so do something when the user finished to draw the rectangle ?

https://github.com/zakodium/react-plot/blob/5ee0ac8f7e09701e364e7e143989ad33d1cfd071/src/hooks/useDrawRectangle.tsx#L5-L15

I was thinking about drawing an area to make peak picking and the process would be done when the user finished to draw the rectangle.

**Comment by targos** [comment]
How would it be different from onDraw?

**Comment by lpatiny** [comment]
It is executed only one time at the end of drawing the rectangle. Peak picking could take some time (like the multiplet peak picking in NMR).

onDraw is executed at each mouse move right ?

**Comment by stropitek** [comment]
> onDraw is executed at each mouse move right ?

no it' called on end: https://github.com/zakodium/react-plot/blob/5ee0ac8f7e09701e364e7e143989ad33d1cfd071/src/hooks/useDrawRectangle.tsx#L26-L37

**Comment by targos** [comment]
Closing as `onDraw` is already called on end.
