### ISSUE TITLE
fix stories with tracking

### ISSUE THREAD

**Issue by stropitek** [zakodium/react-plot#314]
https://zakodium.github.io/react-plot/?path=/story/api-tracking--tracking-example
https://zakodium.github.io/react-plot/?path=/story/api-tracking--tracking-big

Those 2 stories seem to be broken

@lpatiny can you confirm before assigning to Wadjih?

**Comment by lpatiny** [comment]
Yes they are indeed broken but I guess they should be redone with the new useStartMoveEnd hook.

Should it be a 'useTracking' hook that extends useStartMoveEnd ?

Should this hook returns an object containing 'annotations' like the zoom ?

This hook would accept a callback that needs to return 'annotations' that will be placed in the spectrum.

```ts
const tracker = useTracking({
    onMove: (event) => {
      return <Text
          x={coordinates.x}
          y={coordinates.y}
        >{coordinates.x.toFixed(2) + ' / ' + coordinates.y.toFxied(2)}
        </text>;
    },
  });
```
Tracking information should disappear when leaving the plot.
Of course the example could be a little bit more fancy with a groups that contains a bullet annotation on the closest point and text hover.

**Comment by stropitek** [comment]
I'll give this a try

**Comment by lpatiny** [comment]
Some ideas:

![2022-02-08 21 36 16](https://user-images.githubusercontent.com/1484241/153071384-d11090f6-4c14-4589-8052-9a64ba9d07a4.gif)

Being able to highlight the position of the series but also the list of the values in a kind of legend. To do this you need the little component that has the same style as the series.

![2022-02-08 21 39 32](https://user-images.githubusercontent.com/1484241/153071886-7568d9f4-433c-4e25-8436-e35f99e13711.gif)

![image](https://user-images.githubusercontent.com/1484241/153071869-4182b823-3b4d-4c0b-beb9-809e175b9d01.png)
