### ISSUE TITLE
paddingStart / paddingEnd on axis and units

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#319]
What should be the units for paddingStart and paddingEnd ?

It seems that currently is should be a number between 0 and 1.

I would suggest that we have the choice like with the other components and that we could use:
- "10" for 10 pixels
- "20%" for 20% of the width
- 0.2 for the space based on the axis units (not sure it is useful).

@targos What do you think ?

**Comment by targos** [comment]
We need to discuss padding because it's a source of issues now with the zoom hooks and the mouse events.
