### ISSUE TITLE
Scatter plot

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#32]
Add the possibility to have scatter plots.

Some how scatter plots should use the same code as markers

You may use the iris dataset https://github.com/mljs/dataset-iris as an example. One different color per category.

Would be nice to have also regression line per category. You may use our library to make the regression.

**Comment by maasencioh** [comment]
a scatter plot by definition should be a different component by the lack of order in their inputs, should we add it to this same package?

Also if always will have a category we could add a property or even a component `ScatterPlot.Category data={[ ... ]} label="setosa" />`

Another thing to consider is that a component that works for visualization doesn't necessarily need to make this kind of calculations, but allows a way to add that information.

What do you think @targos @stropitek ?

**Comment by targos** [comment]
It shouldn't be an entirely different component. Rather a different `ScatterSeries` component. It's important that we are able to mix scatter and line series in the same plot

**Comment by maasencioh** [comment]
closed in #45
