### ISSUE TITLE
Add ParallelAxis tick Format 

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium/react-plot#320]
i think this feature will be so usefull 
if we want to display two diffrent units in same time ( F° and C°  for example)

**Comment by lpatiny** [comment]
Sounds interesting indeed but I don't see how you would implement it.

There would be a callback on the second axis to convert the values ?

Could you give us a code example about how it would look like ?

**Comment by wadjih-bencheikh18** [comment]
<Plot {...DEFAULT_PLOT_CONFIG}>
      <LineSeries data={data} xAxis="x" yAxis="y" />
      <Axis id="x" position="bottom" label="Celsius" />
      <Axis id="y" position="left" label="Y" />
      <ParallelAxis   id= 'x' label='Fahrenheit'  tickFormat ={(x)=>(x*9/5 + 32)} />
 </Plot>
