### ISSUE TITLE
useLassoSelection

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#338]
This advanced hook would allow to select points in scatter series.

- this would useDrawPath
- by default it should be filled. I would suggest contour line in black 2 points thick and filled with black translucent: 0.8
- accepts a callback that receives for each scatter series (and only the scatter series) all the points that are inside the lasso selection
- we need a way to highlight the selected points that are selected

**Comment by lpatiny** [comment]
Could first be done in a story, no need to create any hook.

The following dependency could be used: https://www.npmjs.com/package/point-in-polygon

We can take the PCA data of ecstasy but in a new story.

![2022-02-17 11 05 14](https://user-images.githubusercontent.com/1484241/154453087-fc7723f0-df07-4035-9afb-e9a2ff0fc2d2.gif)

**Comment by wadjih-bencheikh18** [comment]
i see that useDrawPath is made using polyline and we should make a new version with polygone (add a prop if we want it polyline /polygone ) to be like the example (the first point is attached to the last one )
