### ISSUE TITLE
Add property 'display' on the axis

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#34]
By default 'display' is true but you may want to hide an axis (and the corresponding label).

**Comment by maasencioh** [comment]
If you don't add the axis component it won't be displayed

**Comment by targos** [comment]
Yes, but if you want to "zoom" by setting a `min` and `max` you have to add the axis

**Comment by maasencioh** [comment]
I will be really lost zooming in an axis that is not rendering, but I can add it then

**Comment by lpatiny** [comment]
Most of the spectra we don't display vertical scale and nevertheless we vertical scale them.

Each time we do a suggestion it really looks like you try to avoid to do any improvement.

**Comment by maasencioh** [comment]
> Each time we do a suggestion it really looks like you try to avoid to do any improvement.
My job is to do improvements, when I make these questions is to understand the problem and how to solve it, not to avoid any work.

This will also hide the grid?

**Comment by targos** [comment]
I think it shouldn't hide the grid because there's already a specific prop for that. It should hide the axis bar, the ticks, the tick labels and potentially the axis label (not sure it makes sense to display a label alone)

**Comment by lpatiny** [comment]
Could not see it in the examples. Did you plan that axis can be hidden separately ? Often we need to hide Y axis while keeping X axis visible.

**Comment by maasencioh** [comment]
yes, is a property for each axis, in the storybook I just send a prop for simplification (same as `showGrid` property)

**Comment by maasencioh** [comment]
> Could not see it in the examples

Is the `showAxis` property in the controller https://zakodium.github.io/react-plot/?path=/story/plot-general-options--control
