### ISSUE TITLE
Rename paddingStart / paddingEnd to paddingMin / paddingMax ?

### ISSUE THREAD

**Issue by lpatiny** [zakodium/react-plot#343]
I'm wondering if paddingStart and paddingEnd should not be renamed to paddingMin and paddingMax to avoid ambiguities.

I think that currently for the horizontal axis paddingStart is always on the left even if the axis is reversed and I'm not sure it is obvious.

**Comment by targos** [comment]
> I think that currently for the horizontal axis paddingStart is always on the left even if the axis is reversed and I'm not sure it is obvious.

That's not true. The padding is flipped too when you flip the axis.

**Comment by targos** [comment]
We used start/end terminology because it looks like CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-start

Also I think it's better to keep min/max for the characteristic of a value, not a position.
