### ISSUE TITLE
use many Series in the same Plot bug

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium/react-plot#347]
when we put lineSeries before BarSeries , the latter will no longer be visible

Example :
```
<Plot {...DEFAULT_PLOT_CONFIG}>
      <LineSeries data={data2} />
      <BarSeries data={data2} />
      <Axis id="x" position="bottom" label="time [s]" />
      <Axis id="y" position="left" />
</Plot>
 ```
![image](https://user-images.githubusercontent.com/56769876/154844395-db2a6e44-b940-4afd-aad7-ad9109c05101.png)

**Comment by wadjih-bencheikh18** [comment]
i think the problem is due to fill proprety in LineSeries path

**Comment by targos** [comment]
What is the bug?

**Comment by wadjih-bencheikh18** [comment]
okey i'm going to try

**Comment by targos** [comment]
Yes, I can see it now, please describe bugs with words in the issue and use screenshot only to illustrate.
At first, I thought the bug was about the color.

**Comment by wadjih-bencheikh18** [comment]
@targos can start working on this issue?

**Comment by targos** [comment]
yes!

**Comment by wadjih-bencheikh18** [comment]
thanks

**Comment by wadjih-bencheikh18** [comment]
i found that it was the same problem as mass example 
Solved here https://github.com/zakodium/react-plot/pull/351
we can close this issue
