### ISSUE TITLE
color scaler should use series id instead of label

### ISSUE THREAD

**Issue by targos** [zakodium/react-plot#37]
the label is optional and if it is not passed, all series will have the same color

**Comment by maasencioh** [comment]
The idea behind this was to give the same color for the same label (if there's this case), should we then do something like this instead?

```ts
const labels = state.series.map(({ id, label }) => label || id);
```

**Comment by targos** [comment]
> give the same color for the same label 

I'm not sure we should do that. Do you know other plot libraries with this behavior (not necessarily in JS) ?

/cc @lpatiny

**Comment by lpatiny** [comment]
I don't know about this feature in other libraries.

It would be nice in the storybook to have the different color models.
- color scaler
- color blind color palette (default behaviour when superimposing many series)

**Comment by maasencioh** [comment]
@lpatiny  The default color selection is the most [color blind that I found in D3](https://github.com/d3/d3-scale-chromatic#schemeSet1). But it will receive an array of colors as well, that's what you mean with color scaler?

@targos what do you think if we use the id for the moment, but adds a `groupId` later, to use the same color for a group? 

![example](https://www.researchgate.net/profile/Stefan_Tenbohlen/publication/321356762/figure/fig2/AS:651867319197713@1532428688390/Comparison-of-IV-curves-of-the-MOSFET-in-the-first-qudrant.png)
