### ISSUE TITLE
API to put legend inside the plot

### ISSUE THREAD

**Issue by targos** [zakodium/react-plot#51]

**Comment by targos** [comment]
- "absolute" positioning relative to the viewport
- top, left, bottom, right props

**Comment by lpatiny** [comment]
```js
    legend: {
        position: 'right', // embedded, left, top, bottom
        top: "20px", // or 20%
        bottom: "20px", // should never specify top and bottom or right and left
        right: "50px",
        left: "30px",
        horizontalAlign: "top", // default value depends of the other parameters
        verticalAlign: "center", // default value depends of the other parameters
    }
```

**Comment by maasencioh** [comment]
`horizontalAlign` and `verticalAlign` should be equivalent to the (`alignment-baseline`)[https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline] and (`text-anchor`)[https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor] ?

**Comment by targos** [comment]
How do you plan on doing the alignment? Is there some SVG/CSS property that we can use?
