### ISSUE TITLE
Replace XAxis/YAxis with Axis

### ISSUE THREAD

**Issue by targos** [zakodium/react-plot#60]
- each axis has an `id`, which must be unique and by default is `x` for a horizontal axis and `y` for a vertical axis
- use the "position" prop to determine where the axis is
- validate that the series specifies xAxis (default `x`) and yAxis (default `y`) correctly (orthogonal)
- throw if 2 axes have the same position

**Comment by maasencioh** [comment]
If two axes have the same id doesn't throw if are in the same direction:
```tsx
{/* This displays the same axis on the left and right position */}
<Axis position='left' id='y' />
<Axis position='right' id='y' />
```

**Comment by targos** [comment]
I like option 1, because it allows to customize some props differently for each position.

**Comment by targos** [comment]
We need to think about how this will work on the PlotObject.

**Comment by maasencioh** [comment]
In the first case, the key of the PlotObject could be the position, and for the second case the id. Another way is to make the object an array of objects.

**Comment by targos** [comment]
+1 to an array of objects. The Plot component could transform the JSX to that as well so we have the same implementation.
